openapi: 3.0.1
info:
  description: "C'est pour le cours d'Api de Monsieur Quentin"
  version: "1.0.6"
  title: "Tp WebNovel-API"
servers:
  - url: '{protocol}://{server}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      server:
        default: localhost:3000
paths:
  /webnovels:
    get:
      tags:
        - "WebNovels"
      summary: "Obternir la liste des webnovels"
      description: "getAllNovels"
      operationId: "NovelsList"
      parameters:
        - name: webnovels
          in: query
          description: "Une liste de webnovels"
          required: false
          schema:
            type: array
            items:
             type: object
      responses:
        "200":
          description: "Obternir la liste des webnovels"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebnovelList"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - WebNovels
      security:
        - bearerAuth: []
      summary: Ajouter un webnovel à l'api
      operationId: addWebnovel
      requestBody:
        $ref: "#/components/requestBodies/WebnovelCreation"
      responses:
        "201":
          $ref: "#/components/responses/ResourceCreated"
        "400":
          $ref: "#/components/responses/InvalidBody"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  parameters:
    idInPath:
      required: true
      name: id
      in: path
      schema:
        type: integer
  schemas:
    WebnovelList:
      type: object
      properties:
        success:
          type: boolean
          default: true
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/Webnovel'
    Webnovel:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Webnovel"
        date:
          type: string
          format: date
          example: "2022-10-25"
  requestBodies:
    WebnovelCreation:
      required: true
      description: Webnovel a creer
      content:
        application/json:
          schema:
            required: [title, date]
            allOf:
              - $ref: '#/components/schemas/Webnovel'
  responses:
    ResourceCreated:
      description: "Le webnovel a été créé"
      content:
        application/json:
          schema:
            type: object
            required : [ success, id ]
            properties:
              success:
                type: boolean
                default: true
                example: true
              id:
                type: integer
                example: 1
                description: "L'id du webnovel créée"
    NotFound:
      description: "Le webnovel spécifier est introuvable"
      content:
        application/json:
          schema:
            type: object
            required: [ success, message ]
            properties:
              success:
                type: boolean
                default: false
                example: false
              message:
                type: string
                default: ""
                example: "Le webnovel spécifié avec cette id est introuvable"
    InvalidBody:
      description: "Le body envoyé avec cette requête n'est pas valide"
      content:
        application/json:
          schema:
            type: object
            required: [ success, message ]
            properties:
              success:
                type: boolean
                default: false
                example: false
              message:
                type: string
                default: ""
                example: "Arguments incorrects"
    InternalServerError:
      description: "Internal server erreur"
      content:
        application/json:
          schema:
            type: object
            required: [ success, message ]
            properties:
              success:
                type: boolean
                default: false
                example: false
              message:
                type: string
                default: "Serveur inconnu"
                example: "Serveur inconnu"
      